cleaningSystem/cleaningSystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('taskTeams.urls')),
    path('', include('reservation.urls'))
]

cleaningSystem/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views.custom_logout, name='logout'),
]

cleaningSystem/core/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    ROLE_CHOICES = [
        ('Chief', 'Chief'),
        ('Member', 'Member'),
        ('Client', 'Client'),
        ('Admin', 'Admin'),
    ]
    role = models.CharField(max_length=20, choices=ROLE_CHOICES)

cleaningSystem/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import CustomUser
import re

class LoginForm(AuthenticationForm):
     username = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Your username', 'class':'w-full py-4 px-6 rounded-xl'}))
     password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Your password', 'class':'w-full py-4 px-6 rounded-xl'}))

class SignupForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1', 'password2', 'role')
    
    username = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder':'Your username', 'class':'w-full py-4 px-6 rounded-xl'}),
        error_messages={'required': 'Username is required.'}
    )
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'placeholder':'Your email', 'class':'w-full py-4 px-6 rounded-xl'}),
        error_messages={'required': 'Email is required.'}
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder':'Your password', 'class':'w-full py-4 px-6 rounded-xl'}),
        error_messages={'required': 'Password is required.'}
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder':'Repeat password', 'class':'w-full py-4 px-6 rounded-xl'}),
        error_messages={'required': 'Please confirm your password.'}
    )
    role = forms.ChoiceField(
        choices=CustomUser.ROLE_CHOICES,
        widget=forms.Select(attrs={'class': 'w-full py-4 px-6 rounded-xl'}),
        error_messages={'required': 'Please select a role.'}
    )
    
    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("The two password fields must match.")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        if not user.role:
            user.role = 'Member'  # Default role can be 'Member'
        if commit:
            user.save()
        return user

cleaningSystem/core/views.py
from django.shortcuts import render, redirect
from .forms import SignupForm
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from taskTeams.models import Profile
from django.contrib import messages
from django.contrib.auth import logout
from.models import CustomUser

# Create your views here.
def index(request):
    return render(request, 'core/base.html')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        
        if form.is_valid():
            user = form.save()  # Save the form and get the user instance
            login(request, user)  # Automatically log in the user after successful signup
            
            # Optionally, add a success message
            messages.success(request, "Account created successfully! Welcome.")
            
            return redirect('/login/')
    else:
        form = SignupForm()
    
    return render(request, 'core/signup.html', {
        'form': form
    })

@receiver(post_save, sender=CustomUser)  # Use CustomUser here
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=CustomUser)  # Use CustomUser here
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

def custom_logout(request):
    logout(request)
    return redirect('/')

cleaningSystem/core/templates/core/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <title> {% block title %}{% endblock title %} | Cleaning_System</title>
  </head>
  <body>
    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
      <a href="/" class="text-xl font-semibold">Ease Clean</a>
      <div class="space-x-6">
        {% if request.user.is_authenticated %}
          <div class="flex items-center space-x-4">
            <img src="https://cdn-icons-png.flaticon.com/512/9203/9203764.png" alt="Profile Icon" class="w-10 h-10 rounded-full">
            <div>
              <p class="text-lg font-medium">{{ request.user.username }}</p>
              <p class="text-sm text-gray-500 capitalize">{{ request.user.role }}</p>
            </div>
            <form method="post" action="{% url 'core:logout' %}">
              {% csrf_token %}
              <button type="submit" class="px-4 py-2 text-sm bg-red-500 text-white rounded-lg hover:bg-red-700">
                Logout
              </button>
            </form>
          </div>
        {% else %}
          <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign Up</a>
          <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Login</a>
        {% endif %}
      </div>
    </nav>    
    <div class="px-6 py-6">
      {% block content %}

      {% endblock %}
    </div>
    <footer class="py-6 px-6 flex justify-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400">About</h3>
            <p class="text-lg text-gray-500">Schedule professional cleaning services at your fingertips. Choose from a variety of cleaning packages and expert cleaners to suit your needs. Sit back, relax, and let us handle the rest.</p>
        </div>
        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
            <ul class="space-y-2">
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Term of use</a></li>
            </ul>
        </div>
    </footer>
  </body>
</html>

cleaningSystem/core/templates/core/baseForm.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://cdn.tailwindcss.com"></script>
    <title> {% block title %}{% endblock title %} | Cleaning_System</title>
  </head>
  <body>
    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
        <a href="/" class="text-xl font-semibold">Ease Clean</a>
        <div class="space-x-6">
            {% if request.user.is_authenticated %}
            <a href=" {% url 'core:logout' %} " class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Logout</a>
            <a href="#" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
            {% else %}
            <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign Up</a>
            <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Login</a>
            {% endif %}
        </div>
    </nav>
    <div class="px-6 py-6">
      {% block content %}

      {% endblock %}
    </div>
    <footer class="py-6 px-6 flex justify-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400">About</h3>
            <p class="text-lg text-gray-500">Schedule professional cleaning services at your fingertips. Choose from a variety of cleaning packages and expert cleaners to suit your needs. Sit back, relax, and let us handle the rest.</p>
        </div>
        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
            <ul class="space-y-2">
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Term of use</a></li>
            </ul>
        </div>
    </footer>
  </body>
</html>

cleaningSystem/core/templates/core/login.html
{% extends 'core/baseForm.html' %}


{% block title %}
    Log in
{% endblock title %}
    

{% block content %}
    <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">Log in</h1>

        <form action="." method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="mb-3">
                <label for="" class="inline-block mb-2">Username</label><br/>
                {{ form.username }}
            </div>
            <div class="mb-3">
                <label for="" class="inline-block mb-2">Password</label><br/>
                {{ form.password }}
            </div>
            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}
                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Login</button>
        </form>
    </div>
{% endblock content %}
    

cleaningSystem/core/templates/core/signup.html
{% extends 'core/baseForm.html' %}

{% block title %}
    Sign up
{% endblock title %}
    
{% block content %}
    <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">Sign up</h1>

        <form action="." method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
            
            <!-- Username field -->
            <div class="mb-3">
                <label for="" class="inline-block mb-2">Username</label><br/>
                {{ form.username }}
            </div>
            
            <!-- Email field -->
            <div class="mb-3">
                <label for="" class="inline-block mb-2">Email</label><br/>
                {{ form.email }}
            </div>
            
            <!-- Password field -->
            <div class="mb-3">
                <label for="" class="inline-block mb-2">Password</label><br/>
                {{ form.password1 }}
            </div>
            
            <!-- Confirm Password field -->
            <div class="mb-3">
                <label for="" class="inline-block mb-2">Confirm Password</label><br/>
                {{ form.password2 }}
            </div>
            
            <!-- Role field -->
            <div class="mb-3">
                <label for="" class="inline-block mb-2">Role</label><br/>
                {{ form.role }}  <!-- Role field rendered here -->
            </div>

            <!-- Error messages -->
            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}
                    {{ form.non_field_errors }}
                </div>
            {% endif %}
                
            <!-- Submit button -->
            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
        </form>
    </div>
{% endblock content %}